version: '3'

services:
    subscription-management-app:
        container_name: subscription-management-app
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - .:/var/www/html
        depends_on:
            - database
        environment:
            PHP_IDE_CONFIG: "serverName=localhost"

    nginx:
        image: nginx:latest
        container_name: nginx
        ports:
            - "80:80"
        volumes:
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - subscription-management-app

    database:
        image: postgres:${POSTGRES_VERSION:-16}-alpine
        environment:
            POSTGRES_DB: postgres
            POSTGRES_PASSWORD: password
            POSTGRES_USER: user
        ports:
            - "5432:5432"
        volumes:
            - database_data:/var/lib/postgresql/data:rw

volumes:
    database_data:
